name:                ProgramConceptClassifier
version:             0.2.0.0
github:              "montymxb/ProgramConceptClassifier"
license:             BSD3
author:              "Benjamin Friedman Wilson"
maintainer:          "friedman.benjamin@gmail.com"
copyright:           "2021 Benjamin Friedman Wilson"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/montymxb/ProgramConceptClassifier#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- process
- syb
- template-haskell
- uniplate
- haskell-src-exts

library:
  source-dirs: src

executables:
  ProgramConceptClassifier-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ProgramConceptClassifier

tests:
  ProgramConceptClassifier-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ProgramConceptClassifier
